site_name: CRUD-VUE
repo_url : https://github.com/marley71/crud
repo_name : GitHub
edit_uri: '#root/docs/'

pages:
    - Home: index.md
    - Component : component.md
    - Widgets: widgets.md
    - Views: views.md
    - Templates: templates.md
    - Actions : actions.md
    - Confs: confs.md
    - Routes: routes.md
    - Server : server.md
    - App : app.md
    - Protocols : protocollo_dati.md
    - Esempi Views : esempi_views.md

theme: readthedocs

markdown_extensions:
  - smarty

extra:
  name : "ciao"
